### ISSUE TITLE
exe创建失败

### ISSUE THREAD

**Issue by BqeriNG** [mrknow001/API-Explorer#10]
执行 python setup.py build 后提示大量dll缺失，还有 cx_freeze以及setuptools的报错

PS G:\Tools\API-Explorer-main> python setup.py build
running build
running build_exe
WARNING: cannot find 'api-ms-win-core-registry-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-heap-l2-1-0.dll'
WARNING: cannot find 'api-ms-win-core-libraryloader-l1-2-0.dll'
WARNING: cannot find 'api-ms-win-eventing-provider-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-security-base-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-string-l2-1-0.dll'
WARNING: cannot find 'api-ms-win-core-threadpool-l1-2-0.dll'
WARNING: cannot find 'api-ms-win-core-errorhandling-l1-1-2.dll'
WARNING: cannot find 'api-ms-win-core-memory-l1-1-3.dll'
WARNING: cannot find 'api-ms-win-core-privateprofile-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-atoms-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-heap-obsolete-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-string-obsolete-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-localization-obsolete-l1-2-0.dll'
WARNING: cannot find 'api-ms-win-core-stringansi-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-sidebyside-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-kernel32-private-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-kernel32-legacy-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-kernel32-legacy-l1-1-1.dll'
WARNING: cannot find 'api-ms-win-core-appinit-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-stateseparation-helpers-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-delayload-l1-1-1.dll'
WARNING: cannot find 'api-ms-win-core-delayload-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-apiquery-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-power-setting-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-power-base-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-service-private-l1-1-0.dll'
WARNING: cannot find 'ext-ms-win-edputil-policy-l1-1-0.dll'
WARNING: cannot find 'ext-ms-win32-subsystem-query-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-fibers-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-rtlsupport-l1-2-2.dll'
WARNING: cannot find 'api-ms-win-core-processthreads-l1-1-3.dll'
WARNING: cannot find 'api-ms-win-core-processthreads-l1-1-2.dll'
WARNING: cannot find 'api-ms-win-core-memory-l1-1-1.dll'
WARNING: cannot find 'api-ms-win-core-memory-l1-1-2.dll'
WARNING: cannot find 'api-ms-win-core-synch-l1-2-1.dll'
WARNING: cannot find 'api-ms-win-core-file-l1-2-2.dll'
WARNING: cannot find 'api-ms-win-core-file-l1-2-4.dll'
WARNING: cannot find 'api-ms-win-core-file-l1-2-1.dll'
WARNING: cannot find 'api-ms-win-core-io-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-io-l1-1-1.dll'
WARNING: cannot find 'api-ms-win-core-job-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-threadpool-legacy-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-threadpool-private-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-largeinteger-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-libraryloader-l1-2-3.dll'
WARNING: cannot find 'api-ms-win-core-libraryloader-l1-2-2.dll'
WARNING: cannot find 'api-ms-win-core-libraryloader-l1-2-1.dll'
WARNING: cannot find 'api-ms-win-core-libraryloader-l2-1-0.dll'
WARNING: cannot find 'api-ms-win-core-namedpipe-l1-2-2.dll'
WARNING: cannot find 'api-ms-win-core-namedpipe-l1-2-1.dll'
WARNING: cannot find 'api-ms-win-core-datetime-l1-1-1.dll'
WARNING: cannot find 'api-ms-win-core-datetime-l1-1-2.dll'
WARNING: cannot find 'api-ms-win-core-sysinfo-l1-2-0.dll'
WARNING: cannot find 'api-ms-win-core-sysinfo-l1-2-1.dll'
WARNING: cannot find 'api-ms-win-core-sysinfo-l1-2-3.dll'
WARNING: cannot find 'api-ms-win-core-processsnapshot-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-processenvironment-l1-2-0.dll'
WARNING: cannot find 'api-ms-win-core-debug-l1-1-1.dll'
WARNING: cannot find 'api-ms-win-core-errorhandling-l1-1-3.dll'
WARNING: cannot find 'api-ms-win-security-base-l1-2-0.dll'
WARNING: cannot find 'api-ms-win-security-appcontainer-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-comm-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-realtime-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-wow64-l1-1-1.dll'
WARNING: cannot find 'api-ms-win-core-wow64-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-wow64-l1-1-3.dll'
WARNING: cannot find 'api-ms-win-core-systemtopology-l1-1-1.dll'
WARNING: cannot find 'api-ms-win-core-systemtopology-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-processtopology-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-namespace-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-file-l2-1-2.dll'
WARNING: cannot find 'api-ms-win-core-file-l2-1-1.dll'
WARNING: cannot find 'api-ms-win-core-file-l2-1-3.dll'
WARNING: cannot find 'api-ms-win-core-xstate-l2-1-0.dll'
WARNING: cannot find 'api-ms-win-core-xstate-l2-1-1.dll'
WARNING: cannot find 'api-ms-win-core-xstate-l2-1-2.dll'
WARNING: cannot find 'api-ms-win-core-localization-l2-1-0.dll'
WARNING: cannot find 'api-ms-win-core-normalization-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-fibers-l2-1-0.dll'
WARNING: cannot find 'api-ms-win-core-fibers-l2-1-1.dll'
WARNING: cannot find 'api-ms-win-core-localization-private-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-appcompat-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-windowserrorreporting-l1-1-1.dll'
WARNING: cannot find 'api-ms-win-core-windowserrorreporting-l1-1-2.dll'
WARNING: cannot find 'api-ms-win-core-windowserrorreporting-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-windowserrorreporting-l1-1-3.dll'
WARNING: cannot find 'api-ms-win-core-console-l1-2-1.dll'
WARNING: cannot find 'api-ms-win-core-console-l2-1-0.dll'
WARNING: cannot find 'api-ms-win-core-console-l2-2-0.dll'
WARNING: cannot find 'api-ms-win-core-console-l3-2-0.dll'
WARNING: cannot find 'api-ms-win-core-psapi-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-psapi-ansi-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-appcompat-l1-1-1.dll'
WARNING: cannot find 'ext-ms-win-oobe-query-l1-1-0.dll'
WARNING: cannot find 'ext-ms-win-packagevirtualizationcontext-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-path-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-winrt-string-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-winrt-error-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-winrt-l1-1-0.dll'
Traceback (most recent call last):
  File "G:\Tools\API-Explorer-main\setup.py", line 33, in <module>
    setup(
  File "G:\Tools\API-Explorer-main\venv\lib\site-packages\cx_Freeze\__init__.py", line 60, in setup
    setuptools.setup(**attrs)
  File "G:\Tools\API-Explorer-main\venv\lib\site-packages\setuptools\__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "G:\Tools\API-Explorer-main\venv\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "G:\Tools\API-Explorer-main\venv\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "G:\Tools\API-Explorer-main\venv\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "G:\Tools\API-Explorer-main\venv\lib\site-packages\setuptools\dist.py", line 967, in run_command
    super().run_command(command)
  File "G:\Tools\API-Explorer-main\venv\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "G:\Tools\API-Explorer-main\venv\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
    self.run_command(cmd_name)
  File "G:\Tools\API-Explorer-main\venv\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "G:\Tools\API-Explorer-main\venv\lib\site-packages\setuptools\dist.py", line 967, in run_command
    super().run_command(command)
  File "G:\Tools\API-Explorer-main\venv\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "G:\Tools\API-Explorer-main\venv\lib\site-packages\cx_Freeze\command\build_exe.py", line 267, in run
    freezer.freeze()
  File "G:\Tools\API-Explorer-main\venv\lib\site-packages\cx_Freeze\freezer.py", line 692, in freeze
    self._freeze_executable(executable)
  File "G:\Tools\API-Explorer-main\venv\lib\site-packages\cx_Freeze\freezer.py", line 298, in _freeze_executable
    self._add_resources(exe)
  File "G:\Tools\API-Explorer-main\venv\lib\site-packages\cx_Freeze\freezer.py", line 764, in _add_resources
    AddIcon(target_path, exe.icon)
SystemError: <built-in function AddIcon> returned NULL without setting an exception

**Comment by mrknow001** [comment]
上面一堆警告，不用管。下面报错是跟图标有关，检查下图标
